### ISSUE TITLE
Issue after upgrade the dart-sdk to 1.24.0

### ISSUE THREAD

**Issue by mrhdias** [VenChat/sqljocky2#9]
Hi, after upgrade the dart-sdk to 1.24.0 i get this issue:
'package:convert/src/percent/decoder.dart': malformed type: line 29 pos 13: cannot resolve class 'ChunkedConverter' from 'PercentDecoder'
    extends ChunkedConverter<String, List<int>, String, List<int>> {

**Comment by mrhdias** [comment]
I fix the issue. I replace the sqljocky with sqljocky2 and the problem is gone.

```
name: rtqueue
version: 0.0.1
description: RT Queue Manager
dependencies:
    logging: any
    sqljocky2:
        git:
            url: git://github.com/VenChat/sqljocky2.git
    json_god: any
    args: any
    sprintf: any
    intl: any
    mailer: any
executables:
    rtqueue: main
```
